### ISSUE TITLE
Import syntax

### ISSUE THREAD

**Issue by sylvaincaillot** [creativetimofficial/vue-now-ui-dashboard-pro#5]
Hello
Any reason why you chose to import the components as:
import DefaultHeader from '@/views/DashboardViews/DefaultHeader'

and your pages as:
const Login = ()=>  import('@/views/DashboardViews/Pages/Login.vue');

Try to look around for explanation concerning these different syntaxes but didn't get much help.

Thank you

**Comment by cristijora** [comment]
Hello again @sylvaincaillot 

The arrow import syntax `() => import(...)` refers to webpack dynamic import or also known as `code splitting`. When you have such an import, that component is imported async into a separate js file and it will be requested only if you use that component somewhere. So if we take the login case, the login code will be only requested (via xhr request) only if you navigate to the login page.

You could actually test that yourself if you navigate to the [http://vuejs.creative-tim.com/vue-now-ui-dashboard-pro/#/dashboard](demo), open chrome devtools (JS section) and then navigate to login page. You should see that in the JS section in devtool one more file will be requested. 

<img width="1408" alt="screen shot 2018-04-10 at 11 29 01 am" src="https://user-images.githubusercontent.com/15955045/38545415-ac48d2b4-3cb2-11e8-9aec-907e94040af2.png">

This is the code for the login page (10kb) but as I said earlier, it's imported async/on demand only if we navigate to the login page. This way we basically make sure that we import the necessary code only when we need it. In this case we saved `10` extra kb from the initial bundle. This might not seem much, but if we have pages that depend on some heavy plugins (e.g fullcalendar) these async imports might actually save a lot and make the initial page load a lot faster. 

Summarizing, async imports are very helpful but make sure you use them in places or for components that might actually make a difference in size. If it's a `2-3kb` saving then it might not make sense to import them async. 

You can extend this approach to components as well. Try to see `fullcalendar` page or the `vector-map` component. 
As a final note, async imports are very useful but be careful with them and don't use them for everything as they might add complexity in some cases. The real use cases for async components are:
- route pages that are heavy/big in size
- separated components that are big in size or depend on some big external libraries (charts, maps, calendar)

Hope this helps.

**Comment by sylvaincaillot** [comment]
Thanks for the detailled explanation, really apreciated. You are a great teacher ;)
